// Code generated by "codegen"; DO NOT EDIT.

package code

import code "github.com/mingyuans/goerr-gen/codegen"

// init register error codes defines in this source code to `github.com/mingyuans/errors`
func init() {
	code.Register(Success, 200, "OK")
	code.Register(ErrUnknown, 500, "Internal server error")
	code.Register(ErrBind, 400, "Error occurred while binding the request body to the struct")
	code.Register(ErrInvalidParams, 400, "Invalid parameter")
	code.Register(ErrValidation, 400, "Validation failed")
	code.Register(ErrTokenInvalid, 401, "Token invalid")
	code.Register(ErrPageNotFound, 404, "Page not found")
	code.Register(ErrTooManyRequests, 429, "You have exceeded the API call rate limit")
	code.Register(ErrDatabase, 500, "Database error")
	code.Register(ErrEncrypt, 401, "Error occurred while encrypting the user password")
	code.Register(ErrSignatureInvalid, 401, "Signature is invalid")
	code.Register(ErrExpired, 401, "Token expired")
	code.Register(ErrInvalidAuthHeader, 401, "Invalid authorization header")
	code.Register(ErrMissingHeader, 401, "The `Authorization` header was empty")
	code.Register(ErrPasswordIncorrect, 401, "Password was incorrect")
	code.Register(ErrPermissionDenied, 403, "Permission denied")
	code.Register(ErrEncodingFailed, 500, "Encoding failed due to an error with the data")
	code.Register(ErrDecodingFailed, 500, "Decoding failed due to an error with the data")
	code.Register(ErrInvalidJSON, 500, "Data is not valid JSON")
	code.Register(ErrEncodingJSON, 500, "JSON data could not be encoded")
	code.Register(ErrDecodingJSON, 500, "JSON data could not be decoded")
	code.Register(ErrInvalidYaml, 500, "Data is not valid Yaml")
	code.Register(ErrEncodingYaml, 500, "Yaml data could not be encoded")
	code.Register(ErrDecodingYaml, 500, "Yaml data could not be decoded")
	code.Register(ErrLockWithFailed, 429, "The resource that is being accessed is locked.Please wait for a moment and try again")
	code.Register(ErrSpannerUnknown, 500, "DB Unknown error")
	code.Register(ErrJobInvalid, 422, "Job is invalid")
	code.Register(ErrJobExists, 409, "Job already exists, please check your unique key")
	code.Register(ErrJobNotFound, 404, "Job not found")
	code.Register(ErrJobRedisUnknown, 500, "DB Unknown error")
	code.Register(ErrJobCancelIsNotAllowed, 403, "The current status is not allowed to be canceled")
	code.Register(ErrJobSQLBuilderUnknown, 500, "SQL Builder Unknown error")
	code.Register(ErrLockFailed, 500, "Lock Failed, please try again later")
	code.Register(ErrRetryingJobIsNotAllowed, 403, "The job is not allowed to be retried")
	code.Register(ErrRunningJobIsNotAllowed, 403, "The job is not allowed to be running")
	code.Register(ErrJobIsAlreadyRunning, 403, "The job is already running")
}
